when:
  - event: push
    branch: main

variables:
  - &registry "registry.container-registry:5000"
  - &helm_image "alpine/helm:4.0.4"
  - &buildkit_config |
      [registry."registry.container-registry:5000"]
      http = true

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx:5-insecure
    settings:
      repo: registry.container-registry:5000/danielhnyk-blog
      registry: *registry
      tag: ${CI_COMMIT_SHA:0:8}
      platforms: linux/amd64
      insecure: true
      buildkit_config: *buildkit_config
      cache_images:
        - registry.container-registry:5000/danielhnyk-blog:cache

  - name: deploy
    image: *helm_image
    environment:
      KUBECONFIG_DATA:
        from_secret: hera_kubeconfig
    commands:
      - mkdir -p ~/.kube
      - echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config
      - helm upgrade --install blog ./chart --namespace apps --rollback-on-failure --timeout 5m --set image.tag=${CI_COMMIT_SHA:0:8}
